version: '2.2'

services:

  # browse to: https://localhost:9443/ibmmq/console/
  mqserver:
    image: nuviosoftware-mq-local
    ports:
      - "1414:1414"
      - "9443:9443"
    container_name: mqserver
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    stdin_open: true
    tty: true
    restart: always